const WORLD_MAX_X = 128;
const WORLD_MAX_Y = 128;

const WORLDGEN_NAME_MAX_LENGTH = 200;

const FOV_MAX_RADIUS = 10;

const TILE_BASE_SIZE = 32;
const TILE_SCALE = 1;
const TILE_SIZE = TILE_BASE_SIZE * TILE_SCALE;

const SCREEN_TILE_COUNT_X = 40;
const SCREEN_TILE_COUNT_Y = 24;

const SCREEN_WIDTH = TILE_SIZE * SCREEN_TILE_COUNT_X;
const SCREEN_HEIGHT = TILE_SIZE * SCREEN_TILE_COUNT_Y;
